

#CFLAGS="-O2 -Wall -pedantic -pthread"
# This delaration is all that is needed, to compile call:
##make -C /lib/modules/$(uname -r)/build M=$(pwd) modules 
obj-m:=simple_char.o

#module:
#	gcc ${CFLAGS} -o mymod simple_char.c
#kernel_clean:

#module_install:


## To be able to use the module a node must be created:
# mknod /dev/mychdrv c 700 0